import { Sparkles } from 'lucide-react'

import { RecommendationBadge } from '@/components/app/Badges'
import { Button } from '@/components/ui/button'
import type { CaseSummary } from '@/lib/types'

export function SummaryPanel({
  summary,
  canGenerate,
  onGenerate,
  generating,
  generateError,
}: {
  summary: CaseSummary | null
  canGenerate: boolean
  onGenerate: () => void
  generating: boolean
  generateError: string | null
}) {
  return (
    <div className="rounded-xl border border-border bg-card p-6">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold text-foreground">AI-Assisted Summary</h2>
        {canGenerate ? (
          <Button variant="outline" size="sm" onClick={onGenerate} disabled={generating}>
            <Sparkles className="size-4" />
            {generating ? 'Generating…' : summary ? 'Regenerate' : 'Generate Summary'}
          </Button>
        ) : null}
      </div>

      {generateError ? <p className="mt-3 text-sm text-destructive">{generateError}</p> : null}

      {summary ? (
        <div className="mt-4">
          <div className="flex items-center gap-2">
            <span className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
              Recommendation
            </span>
            <RecommendationBadge recommendation={summary.recommendation} />
          </div>
          <p className="mt-3 text-sm leading-relaxed text-foreground">{summary.narrative_text}</p>
          <p className="mt-3 text-xs text-muted-foreground">
            Generated by {summary.generated_by_model}
            {summary.token_count !== null ? ` · ${summary.token_count} tokens` : ''} ·{' '}
            {new Date(summary.created_at).toLocaleString()}
          </p>
        </div>
      ) : (
        <p className="mt-4 text-sm text-muted-foreground">
          No summary generated yet. Run verification first so the summary has discrepancies to
          reason about.
        </p>
      )}
    </div>
  )
}
