"""initial schema

Revision ID: 473fa6dcbe98
Revises:
Create Date: 2026-09-23 13:48:31.031307

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "473fa6dcbe98"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applicants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("employer_name", sa.String(length=255), nullable=False),
        sa.Column("hmda_source_id", sa.String(length=255), nullable=False),
        sa.Column("stated_income", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("stated_loan_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("stated_property_value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("stated_dti", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applicants")),
    )
    op.create_index(op.f("ix_applicants_hmda_source_id"), "applicants", ["hmda_source_id"], unique=True)
    op.create_table(
        "policy_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_doc", sa.String(length=500), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_chunks")),
    )
    op.execute("CREATE INDEX ix_policy_chunks_embedding_hnsw ON policy_chunks USING hnsw (embedding vector_cosine_ops)")
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("LOAN_OFFICER", "UNDERWRITER", "ADMIN", name="user_role"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SUBMITTED", "DOCUMENTS_PENDING", "UNDER_REVIEW", "APPROVED", "REFERRED", "DENIED", name="case_status"
            ),
            nullable=False,
        ),
        sa.Column("assigned_underwriter_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["applicant_id"], ["applicants.id"], name=op.f("fk_cases_applicant_id_applicants")),
        sa.ForeignKeyConstraint(
            ["assigned_underwriter_id"], ["users.id"], name=op.f("fk_cases_assigned_underwriter_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
    )
    op.create_index(op.f("ix_cases_applicant_id"), "cases", ["applicant_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("rule_or_evidence", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_audit_log_case_id_cases")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_case_id"), "audit_log", ["case_id"], unique=False)
    op.create_table(
        "case_summaries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("narrative_text", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Enum("APPROVE", "REFER", "DENY", name="recommendation"), nullable=False),
        sa.Column("generated_by_model", sa.String(length=100), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_case_summaries_case_id_cases")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_summaries")),
    )
    op.create_index(op.f("ix_case_summaries_case_id"), "case_summaries", ["case_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("doc_type", sa.Enum("PAYSTUB", "BANK_STATEMENT", "W2", "ID", name="document_type"), nullable=False),
        sa.Column("file_path", sa.String(length=1000), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "ocr_status", sa.Enum("PENDING_OCR", "PROCESSING", "COMPLETED", "FAILED", name="ocr_status"), nullable=False
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_documents_case_id_cases")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(op.f("ix_documents_case_id"), "documents", ["case_id"], unique=False)
    op.create_table(
        "discrepancies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=255), nullable=False),
        sa.Column("stated_value", sa.String(length=255), nullable=False),
        sa.Column("document_value", sa.String(length=255), nullable=False),
        sa.Column("variance_pct", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("severity", sa.Enum("MINOR", "MAJOR", name="discrepancy_severity"), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_discrepancies_case_id_cases")),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["documents.id"], name=op.f("fk_discrepancies_source_document_id_documents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discrepancies")),
    )
    op.create_index(op.f("ix_discrepancies_case_id"), "discrepancies", ["case_id"], unique=False)
    op.create_table(
        "document_embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=255), nullable=False),
        sa.Column("value_text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_document_embeddings_document_id_documents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_embeddings")),
    )
    op.create_index(op.f("ix_document_embeddings_document_id"), "document_embeddings", ["document_id"], unique=False)
    op.execute(
        "CREATE INDEX ix_document_embeddings_embedding_hnsw ON document_embeddings "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.create_table(
        "extracted_fields",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=255), nullable=False),
        sa.Column("extracted_value", sa.String(length=1000), nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("raw_text_snippet", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_extracted_fields_document_id_documents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extracted_fields")),
    )
    op.create_index(op.f("ix_extracted_fields_document_id"), "extracted_fields", ["document_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_extracted_fields_document_id"), table_name="extracted_fields")
    op.drop_table("extracted_fields")
    op.execute("DROP INDEX IF EXISTS ix_document_embeddings_embedding_hnsw")
    op.drop_index(op.f("ix_document_embeddings_document_id"), table_name="document_embeddings")
    op.drop_table("document_embeddings")
    op.drop_index(op.f("ix_discrepancies_case_id"), table_name="discrepancies")
    op.drop_table("discrepancies")
    op.drop_index(op.f("ix_documents_case_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_case_summaries_case_id"), table_name="case_summaries")
    op.drop_table("case_summaries")
    op.drop_index(op.f("ix_audit_log_case_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_cases_applicant_id"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.execute("DROP INDEX IF EXISTS ix_policy_chunks_embedding_hnsw")
    op.drop_table("policy_chunks")
    op.drop_index(op.f("ix_applicants_hmda_source_id"), table_name="applicants")
    op.drop_table("applicants")
    # ### end Alembic commands ###

    # op.drop_table() does not cascade-drop the Postgres enum types it
    # created; without this, a downgrade followed by upgrade fails with
    # "type already exists".
    for enum_name in (
        "user_role",
        "case_status",
        "document_type",
        "ocr_status",
        "discrepancy_severity",
        "recommendation",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
