"""add discrepancy fingerprint to case_summaries

Revision ID: 54a9e3082e44
Revises: ce3f35a3e9b6
Create Date: 2026-09-23 15:00:32.276104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a9e3082e44'
down_revision: Union[str, None] = 'ce3f35a3e9b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_summaries', sa.Column('discrepancy_fingerprint', sa.String(length=64), nullable=False))
    # NOTE: autogenerate again misidentified the raw-SQL HNSW indexes (see
    # the initial migration) as "removed"; that spurious drop/recreate pair
    # has been removed by hand. Those indexes are untouched by this revision.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_summaries', 'discrepancy_fingerprint')
    # ### end Alembic commands ###
